apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: reverse-words
spec:
  host: reversewords.apps.aws-waytech.rh8c21.sandbox1224.opentlc.com
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: "Service"
    name: reverse-words
    weight: 100

